# Generated by Django 3.1.3 on 2020-11-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIT', models.CharField(max_length=11)),
                ('NombreEmpresa', models.CharField(max_length=255)),
                ('NombreSolicitante', models.CharField(max_length=255)),
                ('Cargo', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=10)),
                ('Origen', models.CharField(max_length=255)),
                ('Destino', models.CharField(max_length=255)),
                ('TipoOperacion', models.CharField(max_length=255)),
                ('TipoContenedor', models.CharField(max_length=255)),
                ('Peso', models.FloatField()),
            ],
        ),
    ]
