# Generated by Django 3.1.3 on 2020-11-30 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_cotizacion_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='Fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
