# Generated by Django 3.1.3 on 2020-11-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0005_auto_20201130_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='Peso',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
