# Generated by Django 3.1.3 on 2020-12-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_auto_20201130_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='Peso',
        ),
    ]
